// Expanded dataset with 100+ colleges and enhanced fields
let colleges = [

/* ================= ENGINEERING ================= */
{id:1,name:"IIT Delhi",category:"Engineering",type:"Government",location:"Delhi",fees:200000,rating:4.9,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/IIT_Delhi_Main_Building.jpeg/960px-IIT_Delhi_Main_Building.jpeg",placement:98,accreditation:"NAAC A++",programs:15,infrastructure:4.9,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library","Sports","WiFi","Cafeteria"],avgPackage:1500000,established:1961,isFeature:true,isTrending:true,reviews:4.8,reviewCount:542},
{id:2,name:"IIT Bombay",category:"Engineering",type:"Government",location:"Mumbai",fees:210000,rating:4.9,image:"https://ui-avatars.com/api/?name=IIT%20Bombay&background=00113a&color=fff&size=400",placement:97,accreditation:"NAAC A++",programs:15,infrastructure:4.9,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library","Sports","WiFi","Cafeteria"],avgPackage:1450000,established:1958,isFeature:true,isTrending:true,reviews:4.85,reviewCount:623},
{id:3,name:"IIT Madras",category:"Engineering",type:"Government",location:"Chennai",fees:200000,rating:4.9,image:"https://ui-avatars.com/api/?name=IIT%20Madras&background=00113a&color=fff&size=400",placement:96,accreditation:"NAAC A++",programs:14,infrastructure:4.8,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library","Sports","WiFi","Cafeteria"],avgPackage:1400000,established:1959,isFeature:true,isTrending:false,reviews:4.82,reviewCount:481},
{id:4,name:"IIT Kanpur",category:"Engineering",type:"Government",location:"Kanpur",fees:190000,rating:4.8,image:"https://upload.wikimedia.org/wikipedia/commons/7/75/IIT_Kanpur.jpg",placement:95,accreditation:"NAAC A++",programs:13,infrastructure:4.7,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library","Sports","WiFi"],avgPackage:1380000,established:1959,isFeature:true,isTrending:false,reviews:4.75,reviewCount:356},
{id:5,name:"IIT Kharagpur",category:"Engineering",type:"Government",location:"Kharagpur",fees:180000,rating:4.8,image:"https://ui-avatars.com/api/?name=IIT%20Kharagpur&background=00113a&color=fff&size=400",placement:94,accreditation:"NAAC A++",programs:13,infrastructure:4.7,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library","Sports","WiFi"],avgPackage:1350000,established:1951,isFeature:false,isTrending:false,reviews:4.72,reviewCount:412},
{id:6,name:"BITS Pilani",category:"Engineering",type:"Private",location:"Pilani",fees:300000,rating:4.8,image:"https://ui-avatars.com/api/?name=BITS%20Pilani&background=00113a&color=fff&size=400",placement:92,accreditation:"NAAC A+",programs:12,infrastructure:4.6,entranceExam:"BITSAT",facilities:["Hostel","Lab","Library","Sports","WiFi","Cafeteria"],avgPackage:1250000,established:1972,isFeature:true,isTrending:false,reviews:4.7,reviewCount:398},
{id:7,name:"BITS Goa",category:"Engineering",type:"Private",location:"Goa",fees:300000,rating:4.7,image:"https://ui-avatars.com/api/?name=BITS%20Goa&background=00113a&color=fff&size=400",placement:90,accreditation:"NAAC A",programs:11,infrastructure:4.5,entranceExam:"BITSAT",facilities:["Hostel","Lab","Library","Sports","WiFi"],avgPackage:1200000,established:1992,isFeature:false,isTrending:false,reviews:4.65,reviewCount:287},
{id:8,name:"NIT Trichy",category:"Engineering",type:"Government",location:"Trichy",fees:150000,rating:4.7,image:"https://ui-avatars.com/api/?name=NIT%20Trichy&background=00113a&color=fff&size=400",placement:88,accreditation:"NAAC A",programs:10,infrastructure:4.4,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library","Sports"],avgPackage:950000,established:1964,isFeature:false,isTrending:false,reviews:4.6,reviewCount:245},
{id:9,name:"NIT Surathkal",category:"Engineering",type:"Government",location:"Surathkal",fees:150000,rating:4.7,image:"https://ui-avatars.com/api/?name=NIT%20Surathkal&background=00113a&color=fff&size=400",placement:87,accreditation:"NAAC A",programs:10,infrastructure:4.3,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library","Sports"],avgPackage:920000,established:1979,isFeature:false,isTrending:false,reviews:4.58,reviewCount:198},
{id:10,name:"NIT Warangal",category:"Engineering",type:"Government",location:"Warangal",fees:150000,rating:4.6,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Nitw_main_gate.JPG/960px-Nitw_main_gate.JPG",placement:85,accreditation:"NAAC A",programs:9,infrastructure:4.2,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library"],avgPackage:880000,established:1959,isFeature:false,isTrending:false,reviews:4.55,reviewCount:167},
{id:11,name:"IIIT Hyderabad",category:"Engineering",type:"Private",location:"Hyderabad",fees:250000,rating:4.8,image:"https://ui-avatars.com/api/?name=IIIT%20Hyderabad&background=00113a&color=fff&size=400",placement:93,accreditation:"NAAC A+",programs:12,infrastructure:4.6,entranceExam:"IIIT-HYD Exam",facilities:["Hostel","Lab","Library","Sports","WiFi"],avgPackage:1300000,established:1998,isFeature:true,isTrending:false,reviews:4.73,reviewCount:321},
{id:12,name:"IIIT Delhi",category:"Engineering",type:"Government",location:"Delhi",fees:220000,rating:4.7,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/IIITD_Campus_2024.jpg/960px-IIITD_Campus_2024.jpg",placement:91,accreditation:"NAAC A",programs:11,infrastructure:4.5,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library","WiFi"],avgPackage:1150000,established:2008,isFeature:false,isTrending:false,reviews:4.68,reviewCount:289},
{id:13,name:"BIT Mesra",category:"Engineering",type:"Private",location:"Ranchi",fees:160000,rating:4.5,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Bitmesra.JPG/960px-Bitmesra.JPG",placement:82,accreditation:"NAAC B+",programs:10,infrastructure:4.0,entranceExam:"BIT-SAT",facilities:["Hostel","Lab","Library","Sports"],avgPackage:800000,established:1986,isFeature:false,isTrending:false,reviews:4.5,reviewCount:156},
{id:14,name:"VIT Vellore",category:"Engineering",type:"Private",location:"Vellore",fees:200000,rating:4.4,image:"https://upload.wikimedia.org/wikipedia/commons/4/43/Technology_Tower%28VIT%29.jpg",placement:80,accreditation:"NAAC B+",programs:11,infrastructure:4.1,entranceExam:"VITEEE",facilities:["Hostel","Lab","Library","Sports"],avgPackage:750000,established:1984,isFeature:false,isTrending:false,reviews:4.45,reviewCount:234},
{id:15,name:"SRM University",category:"Engineering",type:"Private",location:"Chennai",fees:220000,rating:4.3,image:"https://ui-avatars.com/api/?name=SRM%20University&background=00113a&color=fff&size=400",placement:78,accreditation:"NAAC B",programs:10,infrastructure:3.9,entranceExam:"SRMJEEE",facilities:["Hostel","Lab","Library"],avgPackage:700000,established:1985,isFeature:false,isTrending:false,reviews:4.35,reviewCount:203},
{id:16,name:"NIT Rourkela",category:"Engineering",type:"Government",location:"Rourkela",fees:155000,rating:4.6,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/RSP_Administrative_Building.png/960px-RSP_Administrative_Building.png",placement:84,accreditation:"NAAC A",programs:9,infrastructure:4.1,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library","Sports"],avgPackage:890000,established:1961,isFeature:false,isTrending:false,reviews:4.52,reviewCount:178},
{id:17,name:"DTU Delhi",category:"Engineering",type:"Government",location:"Delhi",fees:105000,rating:4.5,image:"https://ui-avatars.com/api/?name=DTU%20Delhi&background=00113a&color=fff&size=400",placement:81,accreditation:"NAAC B+",programs:9,infrastructure:4.0,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library"],avgPackage:850000,established:1941,isFeature:false,isTrending:false,reviews:4.48,reviewCount:145},
{id:18,name:"Pune Institute of Technology",category:"Engineering",type:"Government",location:"Pune",fees:140000,rating:4.4,image:"https://upload.wikimedia.org/wikipedia/commons/d/d1/Pune_university_small.jpg",placement:79,accreditation:"NAAC B+",programs:8,infrastructure:3.9,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library"],avgPackage:780000,established:1983,isFeature:false,isTrending:false,reviews:4.42,reviewCount:112},
{id:19,name:"Manipal Institute",category:"Engineering",type:"Private",location:"Manipal",fees:240000,rating:4.6,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/MIT_Academic_Block_1_-_Quadrangle.jpg/960px-MIT_Academic_Block_1_-_Quadrangle.jpg",placement:86,accreditation:"NAAC A",programs:11,infrastructure:4.4,entranceExam:"MIET",facilities:["Hostel","Lab","Library","Sports","WiFi"],avgPackage:1050000,established:1957,isFeature:false,isTrending:false,reviews:4.62,reviewCount:267},
{id:20,name:"CIPET Chennai",category:"Engineering",type:"Government",location:"Chennai",fees:90000,rating:4.2,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Ministry_of_Chemicals_and_Fertilizers.svg/960px-Ministry_of_Chemicals_and_Fertilizers.svg.png",placement:75,accreditation:"NAAC B",programs:6,infrastructure:3.7,entranceExam:"GATE",facilities:["Hostel","Lab","Library"],avgPackage:650000,established:1974,isFeature:false,isTrending:false,reviews:4.25,reviewCount:89},

/* ================= MEDICAL ================= */
{id:21,name:"AIIMS Delhi",category:"Medical",type:"Government",location:"Delhi",fees:50000,rating:4.9,image:"https://ui-avatars.com/api/?name=AIIMS%20Delhi&background=00113a&color=fff&size=400",placement:99,accreditation:"NAAC A++",programs:7,infrastructure:4.9,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital","WiFi","Cafeteria"],avgPackage:950000,established:1956,isFeature:true,isTrending:true,reviews:4.85,reviewCount:456},
{id:22,name:"AIIMS Bhopal",category:"Medical",type:"Government",location:"Bhopal",fees:50000,rating:4.7,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/AIIMS_Bhopal_Building_Front_%286%29.jpg/960px-AIIMS_Bhopal_Building_Front_%286%29.jpg",placement:95,accreditation:"NAAC A",programs:6,infrastructure:4.6,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital"],avgPackage:880000,established:2003,isFeature:false,isTrending:false,reviews:4.7,reviewCount:234},
{id:23,name:"AIIMS Jodhpur",category:"Medical",type:"Government",location:"Jodhpur",fees:50000,rating:4.7,image:"https://ui-avatars.com/api/?name=AIIMS%20Jodhpur&background=00113a&color=fff&size=400",placement:94,accreditation:"NAAC A",programs:6,infrastructure:4.5,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital"],avgPackage:850000,established:2008,isFeature:false,isTrending:false,reviews:4.68,reviewCount:198},
{id:24,name:"CMC Vellore",category:"Medical",type:"Private",location:"Vellore",fees:120000,rating:4.8,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/CMCH_Vellore.JPG/960px-CMCH_Vellore.JPG",placement:96,accreditation:"NAAC A+",programs:8,infrastructure:4.7,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital","WiFi"],avgPackage:920000,established:1900,isFeature:true,isTrending:false,reviews:4.78,reviewCount:367},
{id:25,name:"KGMU",category:"Medical",type:"Government",location:"Lucknow",fees:80000,rating:4.6,image:"https://ui-avatars.com/api/?name=KGMU&background=00113a&color=fff&size=400",placement:90,accreditation:"NAAC A",programs:6,infrastructure:4.2,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital"],avgPackage:780000,established:1911,isFeature:false,isTrending:false,reviews:4.58,reviewCount:145},
{id:26,name:"JIPMER",category:"Medical",type:"Government",location:"Puducherry",fees:60000,rating:4.7,image:"https://upload.wikimedia.org/wikipedia/commons/8/8d/JIPMER.jpg",placement:93,accreditation:"NAAC A",programs:6,infrastructure:4.5,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital"],avgPackage:850000,established:1967,isFeature:false,isTrending:false,reviews:4.65,reviewCount:212},
{id:27,name:"AFMC Pune",category:"Medical",type:"Government",location:"Pune",fees:70000,rating:4.8,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/AFMC_Main_Building.jpg/960px-AFMC_Main_Building.jpg",placement:97,accreditation:"NAAC A+",programs:7,infrastructure:4.6,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital","WiFi"],avgPackage:1000000,established:1893,isFeature:true,isTrending:false,reviews:4.77,reviewCount:289},
{id:28,name:"Manipal Medical College",category:"Medical",type:"Private",location:"Manipal",fees:300000,rating:4.5,image:"https://upload.wikimedia.org/wikipedia/commons/e/e6/Manipal_Teaching_Hospital.jpg",placement:88,accreditation:"NAAC B+",programs:7,infrastructure:4.3,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital"],avgPackage:750000,established:1953,isFeature:false,isTrending:false,reviews:4.52,reviewCount:156},
{id:29,name:"St Johns Medical College",category:"Medical",type:"Private",location:"Bangalore",fees:250000,rating:4.6,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/St-John%27s_College_Oxford_Coat_Of_Arms.svg/960px-St-John%27s_College_Oxford_Coat_Of_Arms.svg.png",placement:89,accreditation:"NAAC A",programs:7,infrastructure:4.4,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital"],avgPackage:800000,established:1963,isFeature:false,isTrending:false,reviews:4.62,reviewCount:198},
{id:30,name:"Grant Medical College",category:"Medical",type:"Government",location:"Mumbai",fees:80000,rating:4.5,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/AIIMS_BBSR.jpg/960px-AIIMS_BBSR.jpg",placement:85,accreditation:"NAAC B+",programs:6,infrastructure:4.0,entranceExam:"NEET",facilities:["Hostel","Lab","Library"],avgPackage:700000,established:1847,isFeature:false,isTrending:false,reviews:4.5,reviewCount:134},
{id:31,name:"BJ Medical College",category:"Medical",type:"Government",location:"Ahmedabad",fees:70000,rating:4.5,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/B_J_Medical_College%2C_Pune.jpg/960px-B_J_Medical_College%2C_Pune.jpg",placement:84,accreditation:"NAAC B+",programs:6,infrastructure:3.9,entranceExam:"NEET",facilities:["Hostel","Lab","Library"],avgPackage:680000,established:1946,isFeature:false,isTrending:false,reviews:4.48,reviewCount:112},
{id:32,name:"Madras Medical College",category:"Medical",type:"Government",location:"Chennai",fees:60000,rating:4.6,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Mmc-new.jpg/960px-Mmc-new.jpg",placement:87,accreditation:"NAAC A",programs:6,infrastructure:4.1,entranceExam:"NEET",facilities:["Hostel","Lab","Library"],avgPackage:720000,established:1835,isFeature:false,isTrending:false,reviews:4.58,reviewCount:167},
{id:33,name:"Osmania Medical College",category:"Medical",type:"Government",location:"Hyderabad",fees:60000,rating:4.4,image:"https://upload.wikimedia.org/wikipedia/commons/f/f1/Osmania_Medical_College_Image.jpg",placement:80,accreditation:"NAAC B",programs:6,infrastructure:3.8,entranceExam:"NEET",facilities:["Hostel","Lab","Library"],avgPackage:650000,established:1947,isFeature:false,isTrending:false,reviews:4.42,reviewCount:89},
{id:34,name:"GMC Nagpur",category:"Medical",type:"Government",location:"Nagpur",fees:60000,rating:4.4,image:"https://ui-avatars.com/api/?name=GMC%20Nagpur&background=00113a&color=fff&size=400",placement:81,accreditation:"NAAC B+",programs:6,infrastructure:3.9,entranceExam:"NEET",facilities:["Hostel","Lab","Library"],avgPackage:660000,established:1901,isFeature:false,isTrending:false,reviews:4.45,reviewCount:101},
{id:35,name:"Amrita Institute",category:"Medical",type:"Private",location:"Kochi",fees:250000,rating:4.5,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Amrita_Hospital_Kochi.jpg/960px-Amrita_Hospital_Kochi.jpg",placement:86,accreditation:"NAAC B+",programs:7,infrastructure:4.2,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital"],avgPackage:780000,established:1990,isFeature:false,isTrending:false,reviews:4.55,reviewCount:143},

/* ================= LAW ================= */
{id:36,name:"NLSIU Bangalore",category:"Law",type:"Government",location:"Bangalore",fees:200000,rating:4.9,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/10th_Asian_Law_Institute_Conference%2C_National_Law_School_of_India_University%2C_Bangalore%2C_India_-_20130524.JPG/960px-10th_Asian_Law_Institute_Conference%2C_National_Law_School_of_India_University%2C_Bangalore%2C_India_-_20130524.JPG",placement:94,accreditation:"NAAC A++",programs:8,infrastructure:4.7,entranceExam:"CLAT",facilities:["Hostel","Lab","Library","Sports","WiFi"],avgPackage:1200000,established:1987,isFeature:true,isTrending:false,reviews:4.82,reviewCount:287},
{id:37,name:"NLU Delhi",category:"Law",type:"Government",location:"Delhi",fees:200000,rating:4.8,image:"https://upload.wikimedia.org/wikipedia/commons/6/6d/National_Law_University%2C_Delhi.jpg",placement:92,accreditation:"NAAC A+",programs:8,infrastructure:4.6,entranceExam:"CLAT",facilities:["Hostel","Lab","Library","WiFi"],avgPackage:1150000,established:1997,isFeature:true,isTrending:false,reviews:4.78,reviewCount:234},
{id:38,name:"NLU Hyderabad",category:"Law",type:"Government",location:"Hyderabad",fees:180000,rating:4.7,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Downtown_hyderabad_drone.png/960px-Downtown_hyderabad_drone.png",placement:89,accreditation:"NAAC A",programs:7,infrastructure:4.4,entranceExam:"CLAT",facilities:["Hostel","Lab","Library"],avgPackage:1050000,established:1998,isFeature:false,isTrending:false,reviews:4.72,reviewCount:198},
{id:39,name:"NLU Jodhpur",category:"Law",type:"Government",location:"Jodhpur",fees:180000,rating:4.6,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/National_Law_School_of_India_University%2C_Bangalore%2C_India_-_20130524-01.JPG/960px-National_Law_School_of_India_University%2C_Bangalore%2C_India_-_20130524-01.JPG",placement:86,accreditation:"NAAC A",programs:7,infrastructure:4.2,entranceExam:"CLAT",facilities:["Hostel","Lab","Library"],avgPackage:950000,established:2003,isFeature:false,isTrending:false,reviews:4.65,reviewCount:156},
{id:40,name:"NLU Bhopal",category:"Law",type:"Government",location:"Bhopal",fees:170000,rating:4.6,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/National_Law_School_of_India_University%2C_Bangalore%2C_India_-_20130524-01.JPG/960px-National_Law_School_of_India_University%2C_Bangalore%2C_India_-_20130524-01.JPG",placement:85,accreditation:"NAAC A",programs:7,infrastructure:4.1,entranceExam:"CLAT",facilities:["Hostel","Lab","Library"],avgPackage:920000,established:2007,isFeature:false,isTrending:false,reviews:4.62,reviewCount:134},
{id:41,name:"Symbiosis Law School",category:"Law",type:"Private",location:"Pune",fees:250000,rating:4.5,image:"https://upload.wikimedia.org/wikipedia/commons/3/36/Symbiosis_Law_School%2C_Pune.jpg",placement:82,accreditation:"NAAC B+",programs:8,infrastructure:4.3,entranceExam:"SLAT",facilities:["Hostel","Lab","Library","Sports"],avgPackage:900000,established:1977,isFeature:false,isTrending:false,reviews:4.55,reviewCount:178},
{id:42,name:"Jindal Global Law School",category:"Law",type:"Private",location:"Sonipat",fees:400000,rating:4.7,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Mohd._Hamid_Ansari_delivering_the_inaugural_address_at_the_%E2%80%9CConference_on_Federalisms_and_Localisms_at_O.P._Jindal_Global_University%2C_Sonipat_and_Europaeum%2C_Oxford_%28U.K.%29%E2%80%9D%2C_at_Sonipat%2C_in_Haryana_on_October_10%2C_2013.jpg/960px-thumbnail.jpg",placement:88,accreditation:"NAAC A",programs:9,infrastructure:4.5,entranceExam:"JGLAT",facilities:["Hostel","Lab","Library","Sports","WiFi"],avgPackage:1100000,established:2009,isFeature:true,isTrending:false,reviews:4.7,reviewCount:212},
{id:43,name:"Christ Law School",category:"Law",type:"Private",location:"Bangalore",fees:200000,rating:4.4,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Christ_University_Hosur_road_Bangalore_4819.JPG/960px-Christ_University_Hosur_road_Bangalore_4819.JPG",placement:79,accreditation:"NAAC B",programs:7,infrastructure:4.0,entranceExam:"CLAT",facilities:["Hostel","Lab","Library"],avgPackage:800000,established:2002,isFeature:false,isTrending:false,reviews:4.48,reviewCount:123},
{id:44,name:"Amity Law School",category:"Law",type:"Private",location:"Noida",fees:220000,rating:4.3,image:"https://ui-avatars.com/api/?name=Amity%20Law%20School&background=00113a&color=fff&size=400",placement:76,accreditation:"NAAC B",programs:7,infrastructure:3.9,entranceExam:"ALSAT",facilities:["Hostel","Lab","Library"],avgPackage:750000,established:2003,isFeature:false,isTrending:false,reviews:4.42,reviewCount:101},
{id:45,name:"ILS Law College",category:"Law",type:"Private",location:"Pune",fees:150000,rating:4.4,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Full_view_of_Saraswati_building%2C_ILS_Law_College%2C_Pune.jpg/960px-Full_view_of_Saraswati_building%2C_ILS_Law_College%2C_Pune.jpg",placement:80,accreditation:"NAAC B+",programs:7,infrastructure:4.1,entranceExam:"CLAT",facilities:["Hostel","Lab","Library"],avgPackage:820000,established:1974,isFeature:false,isTrending:false,reviews:4.5,reviewCount:145},
{id:46,name:"Government Law College",category:"Law",type:"Government",location:"Mumbai",fees:100000,rating:4.6,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Government_Law_College%2C_Mumbai.jpg/960px-Government_Law_College%2C_Mumbai.jpg",placement:87,accreditation:"NAAC A",programs:7,infrastructure:4.2,entranceExam:"CLAT",fees:900000,established:1821,isFeature:false,isTrending:false,reviews:4.62,reviewCount:167},
{id:47,name:"Faculty of Law DU",category:"Law",type:"Government",location:"Delhi",fees:80000,rating:4.7,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Jackman_Law_Building_UofT.jpg/960px-Jackman_Law_Building_UofT.jpg",placement:89,accreditation:"NAAC A",programs:7,infrastructure:4.3,entranceExam:"CLAT",facilities:["Hostel","Lab","Library"],avgPackage:950000,established:1951,isFeature:false,isTrending:false,reviews:4.68,reviewCount:198},
{id:48,name:"Banaras Hindu Law",category:"Law",type:"Government",location:"Varanasi",fees:90000,rating:4.6,image:"https://ui-avatars.com/api/?name=Banaras%20Hindu%20Law&background=00113a&color=fff&size=400",placement:86,accreditation:"NAAC A",programs:6,infrastructure:4.1,entranceExam:"CLAT",facilities:["Hostel","Lab","Library"],avgPackage:880000,established:1919,isFeature:false,isTrending:false,reviews:4.58,reviewCount:134},
{id:49,name:"Aligarh Law Faculty",category:"Law",type:"Government",location:"Aligarh",fees:80000,rating:4.5,image:"https://ui-avatars.com/api/?name=Aligarh%20Law%20Faculty&background=00113a&color=fff&size=400",placement:84,accreditation:"NAAC B+",programs:6,infrastructure:4.0,entranceExam:"CLAT",facilities:["Hostel","Lab","Library"],avgPackage:820000,established:1875,isFeature:false,isTrending:false,reviews:4.52,reviewCount:112},
{id:50,name:"Jamia Law Faculty",category:"Law",type:"Government",location:"Delhi",fees:70000,rating:4.6,image:"https://ui-avatars.com/api/?name=Jamia%20Law%20Faculty&background=00113a&color=fff&size=400",placement:85,accreditation:"NAAC A",programs:6,infrastructure:4.1,entranceExam:"CLAT",facilities:["Hostel","Lab","Library"],avgPackage:880000,established:1920,isFeature:false,isTrending:false,reviews:4.6,reviewCount:145},

/* ================= ARTS ================= */
{id:51,name:"St Stephens College",category:"Arts",type:"Government",location:"Delhi",fees:50000,rating:4.8,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Crest_of_St.Stephens_Coll%2C_UOD.svg/960px-Crest_of_St.Stephens_Coll%2C_UOD.svg.png",placement:85,accreditation:"NAAC A+",programs:12,infrastructure:4.5,entranceExam:"Merit",facilities:["Hostel","Lab","Library","Sports"],avgPackage:450000,established:1881,isFeature:false,isTrending:false,reviews:4.72,reviewCount:198},
{id:52,name:"Lady Shri Ram College",category:"Arts",type:"Government",location:"Delhi",fees:50000,rating:4.8,image:"https://ui-avatars.com/api/?name=Lady%20Shri%20Ram%20College&background=00113a&color=fff&size=400",placement:84,accreditation:"NAAC A+",programs:11,infrastructure:4.4,entranceExam:"Merit",facilities:["Hostel","Library","Sports"],avgPackage:420000,established:1956,isFeature:false,isTrending:false,reviews:4.7,reviewCount:167},
{id:53,name:"Hindu College",category:"Arts",type:"Government",location:"Delhi",fees:50000,rating:4.7,image:"https://upload.wikimedia.org/wikipedia/commons/9/92/Hindu_College_%28Front%29.jpg",placement:82,accreditation:"NAAC A",programs:10,infrastructure:4.2,entranceExam:"Merit",facilities:["Hostel","Library","Sports"],avgPackage:400000,established:1899,isFeature:false,isTrending:false,reviews:4.65,reviewCount:145},
{id:54,name:"Miranda House",category:"Arts",type:"Government",location:"Delhi",fees:50000,rating:4.8,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Front_Lawn_and_College..JPG/960px-Front_Lawn_and_College..JPG",placement:83,accreditation:"NAAC A+",programs:11,infrastructure:4.3,entranceExam:"Merit",facilities:["Hostel","Lab","Library"],avgPackage:410000,established:1948,isFeature:false,isTrending:false,reviews:4.68,reviewCount:156},
{id:55,name:"Presidency College",category:"Arts",type:"Government",location:"Chennai",fees:40000,rating:4.6,image:"https://ui-avatars.com/api/?name=Presidency%20College&background=00113a&color=fff&size=400",placement:80,accreditation:"NAAC A",programs:9,infrastructure:4.1,entranceExam:"Merit",facilities:["Hostel","Library"],avgPackage:380000,established:1840,isFeature:false,isTrending:false,reviews:4.58,reviewCount:123},
{id:56,name:"Loyola College",category:"Arts",type:"Private",location:"Chennai",fees:80000,rating:4.6,image:"https://ui-avatars.com/api/?name=Loyola%20College&background=00113a&color=fff&size=400",placement:79,accreditation:"NAAC A",programs:10,infrastructure:4.2,entranceExam:"Entrance",facilities:["Hostel","Library","Sports"],avgPackage:420000,established:1925,isFeature:false,isTrending:false,reviews:4.6,reviewCount:134},
{id:57,name:"Christ University Arts",category:"Arts",type:"Private",location:"Bangalore",fees:120000,rating:4.5,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Christ_University_Hosur_road_Bangalore_4819.JPG/960px-Christ_University_Hosur_road_Bangalore_4819.JPG",placement:75,accreditation:"NAAC B+",programs:9,infrastructure:4.0,entranceExam:"Entrance",facilities:["Hostel","Library","Sports"],avgPackage:380000,established:1969,isFeature:false,isTrending:false,reviews:4.52,reviewCount:112},
{id:58,name:"Symbiosis Arts",category:"Arts",type:"Private",location:"Pune",fees:150000,rating:4.4,image:"https://ui-avatars.com/api/?name=Symbiosis%20Arts&background=00113a&color=fff&size=400",placement:73,accreditation:"NAAC B",programs:8,infrastructure:3.9,entranceExam:"Merit",facilities:["Hostel","Library"],avgPackage:360000,established:1974,isFeature:false,isTrending:false,reviews:4.48,reviewCount:98},
{id:59,name:"Fergusson College",category:"Arts",type:"Government",location:"Pune",fees:40000,rating:4.6,image:"https://ui-avatars.com/api/?name=Fergusson%20College&background=00113a&color=fff&size=400",placement:81,accreditation:"NAAC A",programs:9,infrastructure:4.1,entranceExam:"Merit",facilities:["Hostel","Library","Sports"],avgPackage:390000,established:1821,isFeature:false,isTrending:false,reviews:4.6,reviewCount:145},
{id:60,name:"St Xavier College",category:"Arts",type:"Private",location:"Mumbai",fees:120000,rating:4.6,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/St._Xavier%E2%80%99s_College%2C_Mumbai_02.jpg/960px-St._Xavier%E2%80%99s_College%2C_Mumbai_02.jpg",placement:80,accreditation:"NAAC A",programs:10,infrastructure:4.2,entranceExam:"Merit",facilities:["Hostel","Library","Sports"],avgPackage:410000,established:1869,isFeature:false,isTrending:false,reviews:4.62,reviewCount:167},
{id:61,name:"Jadavpur Arts",category:"Arts",type:"Government",location:"Kolkata",fees:30000,rating:4.7,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Jadavpur%2CRaja_S.C_Mullick_Road%2C_Kolkata.png/960px-Jadavpur%2CRaja_S.C_Mullick_Road%2C_Kolkata.png",placement:83,accreditation:"NAAC A+",programs:10,infrastructure:4.3,entranceExam:"Merit",facilities:["Hostel","Library","Sports"],avgPackage:400000,established:1934,isFeature:false,isTrending:false,reviews:4.68,reviewCount:156},
{id:62,name:"Calcutta Arts College",category:"Arts",type:"Government",location:"Kolkata",fees:30000,rating:4.5,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Logoxaviers.jpg/960px-Logoxaviers.jpg",placement:78,accreditation:"NAAC B+",programs:8,infrastructure:3.9,entranceExam:"Merit",facilities:["Hostel","Library"],avgPackage:360000,established:1873,isFeature:false,isTrending:false,reviews:4.52,reviewCount:112},
{id:63,name:"Banaras Arts College",category:"Arts",type:"Government",location:"Varanasi",fees:40000,rating:4.6,image:"https://ui-avatars.com/api/?name=Banaras%20Arts%20College&background=00113a&color=fff&size=400",placement:80,accreditation:"NAAC A",programs:8,infrastructure:4.1,entranceExam:"Merit",facilities:["Hostel","Library"],avgPackage:370000,established:1914,isFeature:false,isTrending:false,reviews:4.58,reviewCount:123},
{id:64,name:"Aligarh Arts Faculty",category:"Arts",type:"Government",location:"Aligarh",fees:40000,rating:4.5,image:"https://ui-avatars.com/api/?name=Aligarh%20Arts%20Faculty&background=00113a&color=fff&size=400",placement:77,accreditation:"NAAC B+",programs:8,infrastructure:3.8,entranceExam:"Merit",facilities:["Hostel","Library"],avgPackage:350000,established:1875,isFeature:false,isTrending:false,reviews:4.5,reviewCount:101},
{id:65,name:"Jamia Arts Faculty",category:"Arts",type:"Government",location:"Delhi",fees:40000,rating:4.6,image:"https://ui-avatars.com/api/?name=Jamia%20Arts%20Faculty&background=00113a&color=fff&size=400",placement:81,accreditation:"NAAC A",programs:9,infrastructure:4.1,entranceExam:"Merit",facilities:["Hostel","Library"],avgPackage:380000,established:1920,isFeature:false,isTrending:false,reviews:4.6,reviewCount:134},

/* ================= NEW ENGINEERING COLLEGES ================= */
{id:66,name:"NIT Allahabad",category:"Engineering",type:"Government",location:"Allahabad",fees:148000,rating:4.5,image:"https://ui-avatars.com/api/?name=NIT%20Allahabad&background=00113a&color=fff&size=400",placement:83,accreditation:"NAAC B+",programs:8,infrastructure:4.0,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library"],avgPackage:820000,established:1942,isFeature:false,isTrending:false,reviews:4.52,reviewCount:112},
{id:67,name:"SVNIT Surat",category:"Engineering",type:"Government",location:"Surat",fees:152000,rating:4.4,image:"https://ui-avatars.com/api/?name=SVNIT%20Surat&background=00113a&color=fff&size=400",placement:81,accreditation:"NAAC B+",programs:8,infrastructure:3.9,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library"],avgPackage:780000,established:1961,isFeature:false,isTrending:false,reviews:4.48,reviewCount:98},
{id:68,name:"MNNIT Allahabad",category:"Engineering",type:"Government",location:"Allahabad",fees:145000,rating:4.4,image:"https://ui-avatars.com/api/?name=MNNIT%20Allahabad&background=00113a&color=fff&size=400",placement:80,accreditation:"NAAC B",programs:8,infrastructure:3.8,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library"],avgPackage:750000,established:1961,isFeature:false,isTrending:false,reviews:4.45,reviewCount:87},
{id:69,name:"COEP Pune",category:"Engineering",type:"Government",location:"Pune",fees:142000,rating:4.5,image:"https://ui-avatars.com/api/?name=COEP%20Pune&background=00113a&color=fff&size=400",placement:82,accreditation:"NAAC A",programs:9,infrastructure:4.1,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library","Sports"],avgPackage:840000,established:1854,isFeature:false,isTrending:false,reviews:4.54,reviewCount:125},
{id:70,name:"VJTI Mumbai",category:"Engineering",type:"Government",location:"Mumbai",fees:138000,rating:4.4,image:"https://upload.wikimedia.org/wikipedia/commons/b/b4/VJTI_Quadrangle.jpg",placement:79,accreditation:"NAAC B+",programs:7,infrastructure:3.9,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library"],avgPackage:810000,established:1821,isFeature:false,isTrending:false,reviews:4.48,reviewCount:123},
{id:71,name:"Thapar University",category:"Engineering",type:"Private",location:"Patiala",fees:280000,rating:4.6,image:"https://upload.wikimedia.org/wikipedia/commons/a/a0/Romila_Thapar_%28cropped%29.jpg",placement:85,accreditation:"NAAC A",programs:11,infrastructure:4.3,entranceExam:"TUAT",facilities:["Hostel","Lab","Library","Sports","WiFi"],avgPackage:1000000,established:1956,isFeature:false,isTrending:false,reviews:4.62,reviewCount:156},
{id:72,name:"Shiv Nadar University",category:"Engineering",type:"Private",location:"Chennai",fees:320000,rating:4.7,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Snumaingate.jpg/960px-Snumaingate.jpg",placement:87,accreditation:"NAAC A",programs:12,infrastructure:4.5,entranceExam:"SNAT",facilities:["Hostel","Lab","Library","Sports","WiFi"],avgPackage:1100000,established:2009,isFeature:true,isTrending:true,reviews:4.68,reviewCount:189},
{id:73,name:"Amrita University Engineering",category:"Engineering",type:"Private",location:"Coimbatore",fees:290000,rating:4.5,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Amrita_Vishwa_Vidyapeetham_coimbatore_campus.jpg/960px-Amrita_Vishwa_Vidyapeetham_coimbatore_campus.jpg",placement:82,accreditation:"NAAC A",programs:11,infrastructure:4.2,entranceExam:"AEEE",facilities:["Hostel","Lab","Library","Sports"],avgPackage:920000,established:1994,isFeature:false,isTrending:false,reviews:4.58,reviewCount:134},
{id:74,name:"LPU Engineering",category:"Engineering",type:"Private",location:"Jalandhar",fees:220000,rating:4.2,image:"https://ui-avatars.com/api/?name=LPU%20Engineering&background=00113a&color=fff&size=400",placement:72,accreditation:"NAAC B",programs:10,infrastructure:3.8,entranceExam:"Merit",facilities:["Hostel","Lab","Library"],avgPackage:650000,established:1998,isFeature:false,isTrending:false,reviews:4.35,reviewCount:89},
{id:75,name:"DAIICT Gandhinagar",category:"Engineering",type:"Government",location:"Gandhinagar",fees:190000,rating:4.5,image:"https://ui-avatars.com/api/?name=DAIICT%20Gandhinagar&background=00113a&color=fff&size=400",placement:84,accreditation:"NAAC B+",programs:8,infrastructure:4.1,entranceExam:"GATE",facilities:["Hostel","Lab","Library"],avgPackage:950000,established:2001,isFeature:false,isTrending:false,reviews:4.52,reviewCount:112},

/* ================= NEW MEDICAL COLLEGES ================= */
{id:76,name:"PGIMER Chandigarh",category:"Medical",type:"Government",location:"Chandigarh",fees:55000,rating:4.8,image:"https://ui-avatars.com/api/?name=PGIMER%20Chandigarh&background=00113a&color=fff&size=400",placement:96,accreditation:"NAAC A+",programs:8,infrastructure:4.6,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital"],avgPackage:920000,established:1966,isFeature:true,isTrending:false,reviews:4.74,reviewCount:178},
{id:77,name:"AIIMS Rishikesh",category:"Medical",type:"Government",location:"Rishikesh",fees:50000,rating:4.6,image:"https://ui-avatars.com/api/?name=AIIMS%20Rishikesh&background=00113a&color=fff&size=400",placement:91,accreditation:"NAAC A",programs:6,infrastructure:4.3,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital"],avgPackage:850000,established:2007,isFeature:false,isTrending:false,reviews:4.62,reviewCount:145},
{id:78,name:"SRMC Chennai",category:"Medical",type:"Private",location:"Chennai",fees:280000,rating:4.5,image:"https://ui-avatars.com/api/?name=SRMC%20Chennai&background=00113a&color=fff&size=400",placement:87,accreditation:"NAAC B+",programs:7,infrastructure:4.2,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital"],avgPackage:800000,established:1986,isFeature:false,isTrending:false,reviews:4.55,reviewCount:123},
{id:79,name:"Kasturba Medical College",category:"Medical",type:"Private",location:"Manipal",fees:270000,rating:4.6,image:"https://ui-avatars.com/api/?name=Kasturba%20Medical%20College&background=00113a&color=fff&size=400",placement:89,accreditation:"NAAC A",programs:7,infrastructure:4.4,entranceExam:"NEET",facilities:["Hostel","Lab","Library","Hospital","WiFi"],avgPackage:890000,established:1953,isFeature:false,isTrending:false,reviews:4.62,reviewCount:156},
{id:80,name:"Saveetha Medical College",category:"Medical",type:"Private",location:"Chennai",fees:260000,rating:4.3,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Saveetha_Engineering_College%2C_Main_circular_block_.jpg/960px-Saveetha_Engineering_College%2C_Main_circular_block_.jpg",placement:79,accreditation:"NAAC B",programs:6,infrastructure:3.9,entranceExam:"NEET",facilities:["Hostel","Lab","Library"],avgPackage:720000,established:1996,isFeature:false,isTrending:false,reviews:4.42,reviewCount:98},

/* ================= NEW LAW COLLEGES ================= */
{id:81,name:"Gujarat National Law",category:"Law",type:"Government",location:"Gandhinagar",fees:165000,rating:4.6,image:"https://upload.wikimedia.org/wikipedia/commons/0/02/Gujarat_National_Law_University%2C_Administrative_Block.jpg",placement:87,accreditation:"NAAC A",programs:7,infrastructure:4.2,entranceExam:"CLAT",facilities:["Hostel","Lab","Library"],avgPackage:920000,established:2003,isFeature:false,isTrending:false,reviews:4.6,reviewCount:134},
{id:82,name:"Nirma Law School",category:"Law",type:"Private",location:"Ahmedabad",fees:220000,rating:4.4,image:"https://ui-avatars.com/api/?name=Nirma%20Law%20School&background=00113a&color=fff&size=400",placement:80,accreditation:"NAAC B+",programs:7,infrastructure:4.0,entranceExam:"Merit",facilities:["Hostel","Lab","Library"],avgPackage:800000,established:2003,isFeature:false,isTrending:false,reviews:4.52,reviewCount:112},
{id:83,name:"Flame University Law",category:"Law",type:"Private",location:"Pune",fees:280000,rating:4.5,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/DancingFlames.jpg/960px-DancingFlames.jpg",placement:83,accreditation:"NAAC B+",programs:8,infrastructure:4.2,entranceExam:"Entrance",facilities:["Hostel","Lab","Library","Sports"],avgPackage:870000,established:2008,isFeature:false,isTrending:false,reviews:4.58,reviewCount:145},

/* ================= NEW ARTS COLLEGES ================= */
{id:84,name:"Delhi University - Delhi College of Arts",category:"Arts",type:"Government",location:"Delhi",fees:35000,rating:4.7,image:"https://upload.wikimedia.org/wikipedia/commons/9/92/Hindu_College_%28Front%29.jpg",placement:82,accreditation:"NAAC A",programs:11,infrastructure:4.2,entranceExam:"Merit",facilities:["Hostel","Library","Sports"],avgPackage:380000,established:1792,isFeature:false,isTrending:false,reviews:4.65,reviewCount:145},
{id:85,name:"Ramjas College",category:"Arts",type:"Government",location:"Delhi",fees:45000,rating:4.7,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Ramjas_building.jpg/960px-Ramjas_building.jpg",placement:81,accreditation:"NAAC A",programs:10,infrastructure:4.1,entranceExam:"Merit",facilities:["Hostel","Library","Sports"],avgPackage:370000,established:1962,isFeature:false,isTrending:false,reviews:4.62,reviewCount:134},
{id:86,name:"Ashoka University",category:"Arts",type:"Private",location:"Sonipat",fees:350000,rating:4.8,image:"https://ui-avatars.com/api/?name=Ashoka%20University&background=00113a&color=fff&size=400",placement:88,accreditation:"NAAC A+",programs:14,infrastructure:4.6,entranceExam:"Entrance",facilities:["Hostel","Lab","Library","Sports","WiFi"],avgPackage:520000,established:2010,isFeature:true,isTrending:true,reviews:4.78,reviewCount:234},
{id:87,name:"Cluster University Kangra",category:"Arts",type:"Government",location:"Kangra",fees:25000,rating:4.3,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Sardar_Vallabhbhai_Patel_Cluster_University%2C_Mandi_03.jpg/960px-Sardar_Vallabhbhai_Patel_Cluster_University%2C_Mandi_03.jpg",placement:72,accreditation:"NAAC B",programs:7,infrastructure:3.5,entranceExam:"Merit",facilities:["Library"],avgPackage:280000,established:1994,isFeature:false,isTrending:false,reviews:4.35,reviewCount:67},
{id:88,name:"Indraprastha College for Women",category:"Arts",type:"Government",location:"Delhi",fees:50000,rating:4.7,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/IP_COLLEGE_FOR_WOMEN.jpg/960px-IP_COLLEGE_FOR_WOMEN.jpg",placement:80,accreditation:"NAAC A",programs:10,infrastructure:4.2,entranceExam:"Merit",facilities:["Hostel","Library","Sports"],avgPackage:380000,established:1924,isFeature:false,isTrending:false,reviews:4.62,reviewCount:156},

/* ================= ADDITIONAL ENGINEERING COLLEGES ================= */
{id:89,name:"PEC University of Technology",category:"Engineering",type:"Government",location:"Chandigarh",fees:160000,rating:4.5,image:"https://ui-avatars.com/api/?name=PEC%20University%20of%20Technology&background=00113a&color=fff&size=400",placement:84,accreditation:"NAAC A",programs:9,infrastructure:4.2,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library","Sports"],avgPackage:890000,established:1921,isFeature:false,isTrending:false,reviews:4.58,reviewCount:134},
{id:90,name:"Delhi Technological University",category:"Engineering",type:"Government",location:"Delhi",fees:140000,rating:4.4,image:"https://ui-avatars.com/api/?name=Delhi%20Technological%20University&background=00113a&color=fff&size=400",placement:80,accreditation:"NAAC B+",programs:9,infrastructure:4.0,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library"],avgPackage:820000,established:1941,isFeature:false,isTrending:false,reviews:4.52,reviewCount:123},
{id:91,name:"Netaji Subhas University of Technology",category:"Engineering",type:"Government",location:"Delhi",fees:135000,rating:4.3,image:"https://ui-avatars.com/api/?name=Netaji%20Subhas%20University%20of%20Technology&background=00113a&color=fff&size=400",placement:78,accreditation:"NAAC B",programs:8,infrastructure:3.9,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library"],avgPackage:780000,established:1992,isFeature:false,isTrending:false,reviews:4.48,reviewCount:101},
{id:92,name:"OP Jindal University",category:"Engineering",type:"Private",location:"Sonipat",fees:300000,rating:4.6,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Om_Prakash_Jindal.jpg/960px-Om_Prakash_Jindal.jpg",placement:86,accreditation:"NAAC A",programs:12,infrastructure:4.4,entranceExam:"JEE Main",facilities:["Hostel","Lab","Library","Sports","WiFi"],avgPackage:1050000,established:2005,isFeature:false,isTrending:false,reviews:4.64,reviewCount:178},
{id:93,name:"Chandigarh University Engineering",category:"Engineering",type:"Private",location:"Chandigarh",fees:240000,rating:4.4,image:"https://upload.wikimedia.org/wikipedia/commons/b/b0/Chandigarh_University_Seal.png",placement:79,accreditation:"NAAC B+",programs:10,infrastructure:4.1,entranceExam:"CUET",facilities:["Hostel","Lab","Library","Sports"],avgPackage:850000,established:2012,isFeature:false,isTrending:false,reviews:4.5,reviewCount:145},
{id:94,name:"Chandigarh University Mohali",category:"Engineering",type:"Private",location:"Mohali",fees:260000,rating:4.5,image:"https://upload.wikimedia.org/wikipedia/commons/0/04/UTrade_Solutions_Office_.jpg",placement:81,accreditation:"NAAC A",programs:11,infrastructure:4.2,entranceExam:"CUET",facilities:["Hostel","Lab","Library","Sports","WiFi"],avgPackage:900000,established:2012,isFeature:false,isTrending:false,reviews:4.55,reviewCount:167},
{id:95,name:"Lovely Professional University",category:"Engineering",type:"Private",location:"Jalandhar",fees:230000,rating:4.3,image:"https://ui-avatars.com/api/?name=Lovely%20Professional%20University&background=00113a&color=fff&size=400",placement:74,accreditation:"NAAC B",programs:11,infrastructure:3.9,entranceExam:"Merit",facilities:["Hostel","Lab","Library","Sports"],avgPackage:700000,established:2005,isFeature:false,isTrending:false,reviews:4.42,reviewCount:112},
{id:96,name:"MIT-ADT University",category:"Engineering",type:"Private",location:"Pune",fees:250000,rating:4.4,image:"https://ui-avatars.com/api/?name=MIT-ADT%20University&background=00113a&color=fff&size=400",placement:78,accreditation:"NAAC B+",programs:10,infrastructure:4.0,entranceExam:"Merit",facilities:["Hostel","Lab","Library"],avgPackage:780000,established:1994,isFeature:false,isTrending:false,reviews:4.48,reviewCount:134},
{id:97,name:"Chitkara University Engineering",category:"Engineering",type:"Private",location:"Himachal Pradesh",fees:210000,rating:4.2,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Chitkara_Punjab_Entrance_Gate.jpg/960px-Chitkara_Punjab_Entrance_Gate.jpg",placement:72,accreditation:"NAAC B",programs:9,infrastructure:3.8,entranceExam:"Merit",facilities:["Hostel","Lab","Library"],avgPackage:680000,established:1997,isFeature:false,isTrending:false,reviews:4.38,reviewCount:98},
{id:98,name:"Btech Delhi Institute of Technology",category:"Engineering",type:"Private",location:"Delhi",fees:250000,rating:4.3,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Placement_and_Training_Cell.jpg/960px-Placement_and_Training_Cell.jpg",placement:76,accreditation:"NAAC B",programs:9,infrastructure:3.9,entranceExam:"Merit",facilities:["Hostel","Lab","Library"],avgPackage:750000,established:2008,isFeature:false,isTrending:false,reviews:4.45,reviewCount:89},
{id:99,name:"Punjabi University Engineering",category:"Engineering",type:"Government",location:"Patiala",fees:130000,rating:4.2,image:"https://ui-avatars.com/api/?name=Punjabi%20University%20Engineering&background=00113a&color=fff&size=400",placement:71,accreditation:"NAAC C",programs:7,infrastructure:3.6,entranceExam:"JEE Main",facilities:["Hostel","Lab"],avgPackage:650000,established:1962,isFeature:false,isTrending:false,reviews:4.32,reviewCount:76},
{id:100,name:"University College of Engineering Rajasthan",category:"Engineering",type:"Government",location:"Rajasthan",fees:125000,rating:4.1,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Rajasthan_Technical_University_-_panoramio_%283%29.jpg/960px-Rajasthan_Technical_University_-_panoramio_%283%29.jpg",placement:69,accreditation:"NAAC B",programs:7,infrastructure:3.5,entranceExam:"JEE Main",facilities:["Hostel","Lab"],avgPackage:620000,established:1963,isFeature:false,isTrending:false,reviews:4.28,reviewCount:67}

];

// Scholarships data
const scholarships = [
  {id: 1, name: "Merit-based National Scholarship", amount: 100000, type: "Merit-based", eligibility: "All Categories", link: "All Colleges", description: "For students scoring above 90% in entrance exams"},
  {id: 2, name: "INSPIRE Scholarship", amount: 80000, type: "Merit-based", eligibility: "Science Stream", link: "Engineering, Medical", description: "Innovation in Science Pursuit for Inspired Research"},
  {id: 3, name: "PM E-YUVA Scheme", amount: 50000, type: "Special", eligibility: "All Categories", link: "All Colleges", description: "Scholarships for youth in emerging technologies"},
  {id: 4, name: "National Scholarship Scheme (NSP)", amount: 120000, type: "Need-based", eligibility: "All Categories", link: "All Colleges", description: "Government scholarship for economically weaker sections"},
  {id: 5, name: "GATE Scholarship", amount: 90000, type: "Merit-based", eligibility: "Engineering", link: "Engineering Colleges", description: "For postgraduate students with GATE qualifier"},
  {id: 6, name: "VISVESVARAYA Scholarship", amount: 75000, type: "Merit-based", eligibility: "Engineering", link: "Engineering Colleges", description: "Scholarships for promising engineering students"},
  {id: 7, name: "ICCR Scholarships", amount: 150000, type: "International", eligibility: "All Categories", link: "All Colleges", description: "For international students pursuing higher education"},
  {id: 8, name: "SC/ST Scholarship Scheme", amount: 100000, type: "Category-based", eligibility: "Scheduled Castes/Tribes", link: "All Colleges", description: "Special scholarship for SC/ST category students"},
  {id: 9, name: "OBC Advancement Fund", amount: 85000, type: "Category-based", eligibility: "OBC Students", link: "All Colleges", description: "Educational support for Other Backward Class students"},
  {id: 10, name: "Minority Community Scholarship", amount: 70000, type: "Category-based", eligibility: "Minority Communities", link: "All Colleges", description: "Support for students from minority communities"},
  {id: 11, name: "Sports Excellence Grant", amount: 110000, type: "Sports", eligibility: "All Categories", link: "All Colleges", description: "For students excelling in national/international sports"},
  {id: 12, name: "Women Empowerment Fund", amount: 95000, type: "Gender-based", eligibility: "Female Students", link: "All Colleges", description: "Scholarships to promote women's education"},
  {id: 13, name: "PhD Research Fellowship", amount: 200000, type: "Research", eligibility: "Engineering, Science", link: "All Colleges", description: "Research fellowships for PhD students"},
  {id: 14, name: "CII Scholarship for Professional Excellence", amount: 80000, type: "Merit-based", eligibility: "All Categories", link: "All Colleges", description: "Sponsored by Confederation of Indian Industry"},
  {id: 15, name: "KPMG Scholarship Program", amount: 75000, type: "Corporate", eligibility: "Commerce, Engineering", link: "All Colleges", description: "Corporate scholarship from KPMG Foundation"},
  {id: 16, name: "Infosys Foundation Scholarship", amount: 100000, type: "Corporate", eligibility: "Engineering", link: "Engineering Colleges", description: "Scholarships for aspiring IT engineers"},
  {id: 17, name: "Google STEP Internship", amount: 50000, type: "Internship", eligibility: "Engineering", link: "Engineering Colleges", description: "Internship opportunity with Google Summer Training"},
  {id: 18, name: "Microsoft Scholarship", amount: 85000, type: "Corporate", eligibility: "Technology Stream", link: "Engineering Colleges", description: "Educational support from Microsoft"}
];

export { colleges, scholarships };
